export enum MatchStatus {
  NEW = "NEW",
  MATCH_PENDING = "MATCH_PENDING",
  BOOKING_IN_PROGRESS = "BOOKING_IN_PROGRESS",
  BOOKED = "BOOKED",
  MISSED_SLOT = "MISSED_SLOT",
  REMATCH_REQUIRED = "REMATCH_REQUIRED",
}

export type MatchStatusType =
  | "NEW"
  | "MATCH_PENDING"
  | "BOOKING_IN_PROGRESS"
  | "BOOKED"
  | "MISSED_SLOT"
  | "REMATCH_REQUIRED";

